server {
  listen 8091;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  charset utf-8;
  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;

  location ~ ^/image-proxy(/resource/image/.+)$ {
    resolver 1.1.1.1 8.8.8.8 valid=300s ipv6=off;
    proxy_set_header Host static001.geekbang.org;
    proxy_set_header Referer https://time.geekbang.org/;
    proxy_set_header User-Agent "Mozilla/5.0";
    proxy_ssl_server_name on;
    proxy_pass https://static001.geekbang.org$1$is_args$args;
  }

  location / {
    try_files $uri $uri/ =404;
  }

  error_page 404 /404.html;
  location = /404.html { internal; }
}
